// lang-es.ts

export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {
    'TandC approved': 'Conditions générales de vente approuvées',
    'TandC': 'Conditions générales de vente',
    'Check': 'chèque',
    'seeAll': 'voir tous',
    'Right name': 'Nom du droit',
    'The changes will apply after the next log in': 'Les changements s\'appliqueront lors de la prochaine connexion',
    'Client view': 'Vue client',
    'Global view': 'Vue globale',
    'Why?': 'Dites nous Pourquoi ?',
    'Edit Event': 'Editer rendez-vous',
    'Move Event': 'Déplacer rendez-vous',
    'check': 'chèque',
    'Clear all Rights': 'Supprimer tous les droits',
    'Week': 'Semaine',
    'Main user': 'Utilisateur principal',
    'Right': 'Droit',
    'read': 'lecture',
    'write': 'écriture',
    'Set all Rights': 'Appliquer tous les droits',
    'Add a type of right': 'Ajouter un type de droit',
    'Year': 'Année',
    'Email already exists': 'Email existe déjà',
    'Cash': 'Espèce',
    'cash': 'Espèce',
    'Load Template': 'Charger un modèle',
    'Save Template': 'Sauvegarder le modèle',
    'Client Calendar': 'Calendrier du client',
    'Prefix Quote': 'Prefixe Devis',
    'Prefix Invoice': 'Prefixe Facture',
    'Prefix Intervention': 'Prefixe Intervention',
    'Upload': 'Télécharger',
    'Add document': 'Ajouter un document',
    'Take a picture': 'Prendre une photo',
    'Great!': 'Enregistré!',
    'No results.': 'Pas de résultats.',
    'VAT. Example: 20': 'TVA. Example: 20',
    'Send by Email:': 'Envoyer par mail : ',
    'Repairer': 'Réparateur',
    'Address line 2': 'Complément d´adresse',
    'Save Card': 'Sauvegarder la carte',
    'Card number': 'Numéro de carte',
    'Go to destination': 'Aller chez le client',
    'Call client': 'Appeler le client',
    'Card Exp month': 'Mois d´expiration',
    'Card Exp Year': 'Année d´expiration',
    'Security code': 'Code de sécurité',
    'Invoice informations': 'Informations de facturation',
    'Bank card informations': 'Informations bancaires',
    'Submit': 'Soumettre',
    'Paiement Date': 'Date de paiement',
    'Login': 'Se connecter',
    'Please enter a new password': 'Merci d´entrer un nouveau mot de passe',
    'Welcome!': 'Bienvenue!',
    'Send': 'Envoyer',
    'Please enter a valid email address': 'Merci d\'entrer une adresse mail valide',
    'Please enter a valid email': 'Merci d\'entrer une adresse mail valide',
    'Payment method': 'Mode de paiement',
    'Your password must have at least 6 characters': 'Votre mot de passe doit contenir au moins 6 caractères',
    'Your quotes at you clients place': 'Faites vos devis chez vos clients !',
    'Forgotten password?': 'Mot de passe oublié ?',
    'Back': 'Retour',
    'Password Confirmation': 'Mot de passe',
    'Confirm your password:': 'Confirmation du mot de passe',
    'Month': 'Mois',
    'Promotional code': 'Code promotionel',
    'No commitment!': 'Aucun engagement !',
    'You can unsubscribe anytime. No transaction will be completed until the end of your trial period, in 30 days.': 'Vous pouvez vous désinscrire à tout moment. Aucun prélèvement ne sera effecuté avant la fin de votre periode d\'essai, dans 30 jours.',
    'You can unsubscribe anytime.': 'Vous pouvez vous désinscrire à tout moment.',
    'Disconnect': 'Déconnexion',
    'Plumber': 'Plombier',
    'Locksmith': 'Serrurier',
    'Electrician': 'Électricien',
    'Gardener': 'Paysagiste',
    'Glazier': 'Vitrier',
    'Type Company': 'Type',
    '$ Interventions': '€ Interventions',
    'Company Email': 'Email de l\'entreprise',
    'Interventions paid this year': 'Interventions payée cette année',
    'Interventions paid this month': 'Interventions payée ce mois',
    'Company name': 'Nom de l\'entreprise',
    'Create new Intervention': 'Nouvelle intervention',
    'Password': 'Mot de passe',
    'Outstanding balance': 'Reste à payer',
    'Add': 'Ajouter',
    'Calendar Options': 'Options du calendrier',
    'Meeting': 'Rendez-vous',
    'Register': 'S\'inscrire',
    'Dashboard': 'Tableau de Bord',
    'My Planning': 'Mon Calendrier',
    'Planning': 'Calendrier',
    'My profile': 'Mon profil',
    'Interventions per year': 'Interventions par année',
    'My company': 'Mon Entreprise',
    'Logout': 'Déconnexion',
    'Items per page': 'Eléments par page',
    'Accountancy': 'Comptabilité',
    'Payments': 'Paiements',
    'Payment': 'Paiement',
    'Online payment': 'Paiement en ligne',
    'I approve the': 'Je valide les',
    'Expenses': 'Dépenses',
    'Expense': 'Dépense',
    'Reporting': 'Statistiques',
    'Settings': 'Paramètres',
    'Product': 'Produit',
    'Invoice': 'Facture',
    'Send document to client': 'Envoyer le document par mail',
    'Home': 'Accueil',
    'Edit': 'Modifier',
    'WorkingAddress': 'Réference Chantier',
    'Painfulness': 'Pénibilité',
    'VAT': 'TVA',
    'Number Id': 'Numéro',
    'Appointment': 'Rendez-vous',
    'Length': 'Longeur',
    'Please enter your email below and we will send you password reset instructions.': 'Merci de renseigner votre email.',
    'Edit Quote': 'Edition du devis',
    'Total with taxes': 'Total TTC',

    'Add a product': 'Ajouter un produit',
    'Create a new': 'Créer un nouveau',
    'product': 'produit',
    'Products': 'Produits',
    'Paiement: Stripe Connection': 'Paiement: Connexion avec Stripe',
    'Create an new product': 'Créer un nouveau produit',
    'List': 'Liste',
    'Subscription': 'Abonnement',
    'Price': 'Prix',
    'Name': 'Nom',
    'Suscribe': 'Souscrire',
    'Price without taxes': 'Prix HT',
    'Product Name': 'Nom du Produit',
    'companie': 'Entreprise',
    'Height': 'Hauteur',
    'I confirm to suscribe to the plan:': 'Je confirme choisir le plan : ',
    'Width': 'Largeur',
    'Depth': 'Profondeur',
    'CostPrice': 'Coût',
    'Selling Price': 'Prix de vente',
    'Save': 'Sauvegarder',
    'Delete': 'Supprimer',
    'Project': 'Rendez-vous',
    'Enter your password to approve changes': 'Renseigner votre mot de passe pour valider les changements',
    'Intervention Settings': 'Paramètres d\'intervention',
    'Legal Notice': 'Notes legales',
    'Save & Create project': 'Sauvegarder et Créer Rendez-vous',
    'Issue date': 'Date d\'émission',
    'Expiry date': 'Date d\'expiration',
    'Users': 'Contacts',
    'User': 'Contact',
    'Team': 'Équipe',
    'External Contact': 'Contact Externe',
    'Create a new team member': 'Créer un nouveau membre interne',
    'Create a new external member': 'Créer un nouveau contact externe',
    'Title': 'Titre',
    'Firstname': 'Prénom',
    'Lastname': 'Nom',
    'Type User': 'Fonction',
    'Phone Number': 'Téléphone',
    'Address': 'Adresse',
    'additional address': 'Complément Adresse',
    'city': 'Ville',
    'City': 'Ville',
    'state': 'Pays',
    'State': 'Etat',
    'zip': 'code Postal',
    'Zip': 'Code Postal',
    'Country': 'Pays',
    'Other': 'Autre',
    'Identity': 'Détails',
    'Details': 'Détails',
    'Calendar Color': 'Couleur du calendrier',
    'Surface': 'Surface',
    'Phone': 'Téléphone',
    'Add Picture': 'Ajouter image',
    'New Address': 'Nouvelle Adresse',
    'Mr.': 'M.',
    'Mrs.': 'Mme',
    'Address shipping': 'Adresse Intervention',
    'Address billing': 'Adresse de Facturation',
    'Additional address': 'Complément adresse',
    'New contact person': 'Nouvel interlocuteur',
    'Contact person': 'Interlocuteur',
    'Company': 'Entreprise',
    'Companies': 'Fournisseurs',
    'Billing': 'Facturation',
    'Shipping': 'Intervention',
    'Contact type': 'Fonction',
    'New Contact person': 'Nouvel Interlocuteur',
    'Phone number': 'Téléphone',
    'Status': 'Statut',
    'Details Quote': 'Détails',
    'Items': 'Eléments',
    'Quotes': 'Devis',
    'quote': 'devis',
    'Create a new quote': 'Créer un nouveau Devis',
    'Assigned to me': 'Assigné à Moi',
    'Assigned to': 'Assigné à',
    'Owner': 'Propriétaire',
    'Download PDF': 'Télécharger PDF',
    'Customer': 'Client',
    'Customers': 'Clients',
    'Supplier': 'Fournisseur',
    'Suppliers': 'Fournisseurs',
    'Estimate Number': 'Numéro du devis',
    'Issue Date': 'Date',
    'Expiry Date': 'Date de Validité',
    'Currency': 'Devise',
    'Estimate Template': 'Modèle de Devis',
    'Amounts are': 'Les montants sont',
    'Discount': 'Remise',
    'Subject': 'Sujet',
    'Add Row': 'Ajouter Ligne',
    'Item': 'Objet',
    'Quantity': 'Quantité',
    'nameTemplate': 'Nom du modèle',
    'templateQuote': 'Recherche',
    'Save TemplateQuote': 'Sauvegarder le Modèle',
    'Add new one': 'Ajouter',
    'Create a new Paiement': 'Nouveau Paiement',
    'Please Select': 'Mode de Paiement',
    'Amount': 'Montant',
    'Quote edit date': 'Date Édition',
    'Quote validity date': 'Date de Validité',
    'Quote title': 'Titre du devis',
    'Template': 'Modèle',
    'Price excl tax': 'Prix HT',
    'VAT (%)': 'TVA (%)',
    'Total excl tax': 'Total HT',
    'Category': 'Catégorie',
    'Text': 'Texte',
    'priceWithoutTaxes': 'Prix HT',
    'Reset': 'Recommencer',
    'Unsign': 'Effacer',
    'Quote': 'Devis',
    'Reference Name': 'Nom du Produit',
    'description': 'Description',
    'Unit': 'Unité',
    'Save As Invoice': 'Convertir en Facture',
    'Go to Invoice': 'Consulter Facture',
    'Validate': 'Valider',
    'Show Comments': 'Voir Commentaires',
    'Reference': 'Référence',
    'Paymentquote': 'Encaissement',
    'Sent': 'Envoyée',
    'Date Invoice Paid': 'Date Encaissement',
    'Signed': 'Signé',
    'signed': 'signé',
    'Rejected': 'Refusé',
    'rejected': 'refusé',
    'Pending Approval': 'Attente de signature',
    'Pending': 'En attente',
    'pending': 'en attente',
    'Paid': 'Payé',
    'paid': 'payé',
    'Pictures' : 'Photos',

    'Feb': 'Fev',
    'Apr': 'Avr',
    'May': 'Mai',
    'June': 'Juin',
    'July': 'Juillet',
    'Aug': 'Aout',
    'I want to unscribe': 'Désinscription',
    // 'Signed, pending payment': 'Signé, en attente de règlement',
    'Drawing': 'Dessin',
    'Get invoice': 'Créer Facture',
    'Is Paid': 'Payé',
    'Calendar': 'Calendrier',
    'Start:': 'Débute le :',
    'End:': 'Termine le :',
    'Invoices': 'Factures',
    'invoice': 'Facture',
    'Today': 'Aujourd´hui',
    'project': 'Rendez-vous',
    'Projects': 'Rendez-vous',
    'Ref': 'Référence',
    'Name Project': 'Nom du Rendez-vous',
    'Started': 'En cours',
    'Done': 'Terminé',
    'Assigned To': 'Assigné à',
    'My tasks': 'Mes tâches',
    'Name Task': 'Description tâche',
    'Project sheet': 'Fiche Rendez-vous',
    'task': 'tâche',
    'Tasks': 'Tâches',
    'Add a project': 'Ajouter un projet',
    'Individual' : 'Particulier',
    'right': 'droit',
    'Rights': 'Droits',
    'today': 'aujourd\'hui',
    'month': 'mois',
    'week': 'semaine',


    'day': 'jour',
    'list': 'liste',
    'Companie': 'Entreprise',
    'Companie Email': 'Email Entreprise',
    'Plan': 'Souscription',
    'Terms': 'Conditions',
    'Card': 'Carte bancaire',
    'address_city': 'Ville de la carte',
    'address_country': 'Pays de la carte',
    'address_line1': 'Adresse',
    'address_line2': 'Complément d\'adresse',
    'address_state': 'Etat',
    'address_zip': 'Code Postal',
    'brand': 'Type de carte',
    'country': 'Pays',
    'exp_mont': 'Mois d´expiration',
    'exp_year': 'Année expiration',
    'Funding': 'Financement',
    'last4': 'derniers chiffres de la carte',
    'delete Card': 'Supprimer Carte',
    'Next': 'Suivant',
    'Subscritpion': 'Souscription',
    'interval_count': 'Interval',
    'current_period_start': 'Début dernier abonnement',
    'current_period_end': 'Fin de l´abonnement',
    'deleteSubInStripe': 'Supprimer inscription Stripe',

    'Connect with Stripe': 'Connecter avec Stripe',

    'Add Categ Products': 'Ajouter Catégorie',
    'Product Categories': 'Catégories Produits',
    'SubCategory': 'Sous-Catégorie',
    'Product Type': 'Type de Produit',

    'Monday': 'Lundi',
    'Tuesday': 'Mardi',
    'Wednesday': 'Mercredi',
    'Thursday': 'Jeudi',
    'Friday': 'Vendredi',
    'Saturday': 'Samedi',
    'Sunday': 'Dimanche',

    'First hour of your day. (06:00:00)': 'Heure de début du calendrier (06:00:00)',
    'Last hour of your day. (19:00:00)': 'Heure de fin du calendrier (19:00:00)',
    'Slot Duraation. (01:00:00)': 'Intervalle (01:00:00)',
    'First hour of your daywork. (10:30:00)': 'Heure de début d´activité (10:30:00)',
    'Last hour of your daywork. (17:00:00)': 'Heure de fin d´activité (17:00:00)',
    'Notes legales': 'Notes de devis',
    'legal Approval': 'Conditions à cocher',
    'Quote Legal Notice': 'Informations légales du devis',
    'Invoice Legal Notice': 'Informations légales de la Facture',
    'Your company logo': 'Logo de votre entreprise',
    'Documents Settings': 'Paramétrage des documents',
    'Cost Price': 'Prix d\'achat',
    'Name of Companie': 'Nom de la Société',
    'Type Companie': 'Activité principale',
    'Search': 'Recherche',
    'This action is not reversible. Are you sure you want to delete?': 'Cette action est irréversible. Confirmez-vous la suppression ?',

};
